name: 'Smoke Tests'
description: 'Run Smoke Tests'
inputs:
  command:
    description: 'The uv command to invoke the smoke tests.'
    required: true
runs:
  using: composite
  steps:
    - name: Get package name
      env:
        PKG_NAME: ${{ github.event.repository.name }}
      shell: bash -e {0}
      run: |
        PKG_NAME=${{env.PKG_NAME}}
        PKG_NAME=${PKG_NAME//-/_} # replace hyphens with undescores
        echo PKG_NAME=${PKG_NAME} >> $GITHUB_ENV
    - name: Test Import
      run: ${{ inputs.command }} python -c "import ${{ env.PKG_NAME }}"
      shell: bash -e {0}
    - name: Run Demo
      if: ${{ env.PKG_NAME }} == 'acoular'
      run: ${{ inputs.command }} python -m acoular.demo
      shell: bash -e {0}
