extend-exclude = ["docs/source", ".git"]
line-length = 120

[lint]
select = [
        "A", "ARG", "ASYNC", "B", "EXE", "FBT", "PERF", "S", "SIM", "SLOT", # code correctness & safety
        "BLE", "C90", "DTZ", "E", "F", "FURB", "INP", "PIE", "PGH", "PL", "PT", "PYI", "RSE", "RET", "RUF", "SLF", "TRY", "UP", "W",  #  sanitization
        "C", "C4", "COM", "N", "NPY", "PTH", "Q", # formatting
        "I", "ICN", "TID",  # imports
        "D", "FIX", "TD",  # docstring
        "EM", "INT", "FLY", "ISC", "G", "LOG", "T20",  # strings, logging & error messages
        # "CPY",  # preview
        ]

ignore = [
    "C901", # do we want to measure code complexity -> TBD
    "COM812", # conflict with ruff formatter
    "D401", # first line should be in imperative mood -> TBD
    "Q000", "Q003",  # we use single quotes
]

[lint.flake8-import-conventions]
banned-from  = ["numba", "numpy", "scipy.linalg"]
[lint.flake8-import-conventions.aliases]
acoular = "ac"
numba = "nb"
numpy = "np"
"scipy.linalg" = "spla"
"matplotlib.pyplot" = "plt"

# custom sort order to prevent wrong load order due to numpy/numba threading issue
[lint.isort]
section-order = ["future", "standard-library", "acoular", "first-party", "local-folder", "third-party"]
[lint.isort.sections]
acoular = ["acoular", "spectacoular", "acoupipe"]

[lint.pycodestyle]
ignore-overlong-task-comments = true
max-doc-length = 100

[lint.pydocstyle]
convention = "numpy"

[format]
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = 120
