name: Conda 🐍 Build 🛠️
permissions:
  contents: read
on:
  workflow_call:

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
      - name: Install conda-build
        run: conda install --yes -n base conda-build
      - name: Check out a copy of the repository
        uses: actions/checkout@v7.0.1
      - name: Set up uv
        uses: astral-sh/setup-uv@v9.0.0
      - name: Build package
        run: |
          export VERSION=$(uvx hatchling version)  # use hatch-vcs here until uv supports dynamic versions. track: https://github.com/astral-sh/uv/issues/14137
          conda run -n base conda build --channel acoular --channel conda-forge --no-anaconda-upload --no-copy-test-source-files recipe.local --output-folder ./conda-pkg
      - name: Store the distribution packages
        uses: actions/upload-artifact@v7.0.1
        with:
          name: conda-build
          path: conda-pkg/
