name: Docs 📝 Build 🛠️ & Deploy
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      deploy:
        required: false
        default: false
        type: boolean
      html_baseurl:
        required: false
        default: ''
        type: string
      docs_version_match:
        required: false
        default: ''
        type: string
      artifact_name:
        required: false
        default: 'build-docs'
        type: string
      artifact_path:
        required: false
        default: './docs/build/html'
        type: string
      setup_portaudio:
        description: 'Whether PortAudio should be installed.'
        type: boolean
        required: false
        default: true

concurrency:
  group: docs-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v6
      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ vars.LATEST_PYTHON_VERSION }}
      - name: Set up Pandoc  # for AcouPipe
        uses: acoular/ci/.github/actions/setup-pandoc@main
        with:
          os: ${{ matrix.os }}
      - name: Set up PortAudio
        if: ${{ inputs.setup_portaudio }}
        uses: acoular/ci/.github/actions/setup-portaudio@main
        with:
          os: ${{ matrix.os }}
      - name: Set up Graphviz
        uses: acoular/ci/.github/actions/setup-graphviz@main
        with:
          os: ${{ matrix.os }}
      - name: Run sphinx
        env:
          DOCS_BASEURL: ${{ inputs.html_baseurl }}
          DOCS_VERSION_MATCH: ${{ inputs.docs_version_match }}
        run: uv run --frozen --exact --group docs make -C docs html
      - name: Upload artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
