name: Package Documentation Deploy
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      artifact_name:
        required: false
        default: build-docs
        type: string
      package:
        required: true
        type: string
      version:
        required: true
        type: string
      min_version:
        required: false
        default: ''
        type: string
      deploy_switcher:
        required: false
        default: false
        type: boolean
    secrets:
      website_gh_pages_token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare payload
        run: mkdir -p "./payload/${{ inputs.package }}/${{ inputs.version }}"
      - name: Generate switcher.json
        if: ${{ inputs.deploy_switcher }}
        uses: acoular/ci/.github/actions/generate-switcher@main
        with:
          package-path: ${{ inputs.package }}
          min-version: ${{ inputs.min_version }}
          output: "payload/${{ inputs.package }}/_static/switcher.json"
      - name: Download build artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifact_name }}
          path: "./payload/${{ inputs.package }}/${{ inputs.version }}"
      - name: Deploy package documentation to website gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: acoular/website
          publish_branch: gh-pages
          personal_token: ${{ secrets.website_gh_pages_token }}
          publish_dir: payload/${{ inputs.package }}
          destination_dir: ${{ inputs.package }}
          keep_files: true
          enable_jekyll: false
