name: PyPI 📦 Build
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      setup_portaudio:
        description: 'Whether PortAudio should be installed.'
        type: boolean
        required: false
        default: false

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v7.0.1
      - name: Set up uv
        uses: astral-sh/setup-uv@v9.0.0
      - name: Set up PortAudio
        if: ${{ inputs.setup_portaudio }}
        uses: acoular/ci/.github/actions/setup-portaudio@main
      - name: Build a binary wheel and a source tarball
        run: uv build
      - name: Run smoke tests (wheel)
        uses: acoular/ci/.github/actions/smoke-tests@main
        with:
          command: uv run --isolated --no-project --with dist/*.whl
      - name: Run smoke tests (sdist)
        uses: acoular/ci/.github/actions/smoke-tests@main
        with:
          command: uv run --isolated --no-project --with dist/*.tar.gz
      - name: Store the distribution packages
        uses: actions/upload-artifact@v7.0.1
        with:
          name: package-build
          path: dist/
